version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mariadb:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22"
      
  mariadb:
      image: mariadb:11.4
      container_name: mariadb
      restart: always
      volumes:
        - db-data:/var/lib/mysql
        - db-config:/etc/mysql/conf.d
      networks:
        - gitea
      environment:
        TZ: 'Asia/Bangkok'
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: gitea
        MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: gitea
      #logging:
      #  driver: syslog
      #  options:
      #    syslog-address: "tcp://127.0.0.1:514"
      #    tag: "mariadb"
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      networks:
        - gitea
      environment:
        TZ: 'Asia/Bangkok'
        PMA_HOST: mariadb
        PMA_PORT: 3306
        PMA_ARBITRARY: 0
        UPLOAD_LIMIT: 1024M
      ports:
        - 8081:80
volumes:
  gitea:
  db-data:
  db-config:

networks:
  gitea:
